### ISSUE TITLE
Physics simulation JS engine

### ISSUE THREAD

**Issue by justinclift** [R0NAND/R0NAND.github.io#1]
Just stumbled over your YouTube video, showing your initial JS physics engine:

https://www.youtube.com/watch?v=J2S7tfLb2A8

As a general thought, there already seem to be lots of JS physics engines around, both 2D and 3D. eg:

* https://github.com/liabru/matter-js ([website](https://brm.io/matter-js/))
* https://www.tapirgames.com/blog/open-source-physics-engines

Depending on your goal, it might be useful to get involved with one of those to move it forward instead of writing your own from scratch? :smile:

**Comment by R0NAND** [comment]
Haha, you do raise a good point, and I know this physics engine is doomed to always be vastly inferior to many others out there. That being said I made this engine to learn Javascript, the low level details of physics engines, and to provide an easily modifyable project to anyone who was interested in playing with the source code. I'll probably still add a few more features and constraint solver improvements for self teaching purposes, but will likely migrate to matter.js and/or Box2D if I work on any bigger projects.

**Comment by justinclift** [comment]
No worries, self-learning experiments are always useful. :smile:
